


export const TEST_A = 'TEST_A'
export const TEST_B = 'TEST_B'

export const REQUEST_TOPIC = 'REQUEST_TOPIC'
export const RECEIVE_TOPIC = 'RECEIVE_TOPIC'

export const START_FAVORITE_TOPIC = 'START_FAVORITE_TOPIC'
export const END_FAVORITE_TOPIC = 'END_FAVORITE_TOPIC'

export const START_THANK_TOPIC = 'START_THANK_TOPIC'
export const END_THANK_TOPIC = 'END_THANK_TOPIC'

export const START_REPLY_TOPIC = 'START_REPLY_TOPIC'
export const END_REPLY_TOPIC = 'END_REPLY_TOPIC'


export const START_THANK_REPLY = 'START_THANK_REPLY'
export const END_THANK_REPLY = 'END_THANK_REPLY'


export const REQUEST_TOPIC_LIST = 'REQUEST_TOPIC_LIST'
export const RECEIVE_TOPIC_LIST = 'RECEIVE_TOPIC_LIST'

export const REQUEST_NODE_LIST = 'REQUEST_NODE_LIST'
export const RECEIVE_NODE_LIST = 'RECEIVE_NODE_LIST'
export const RECEIVE_CATEGORY_NODE_LIST = 'RECEIVE_CATEGORY_NODE_LIST'

export const REQUEST_NODE_PAGE = 'REQUEST_NODE_PAGE'
export const REFRESH_NODE_PAGE = 'REFRESH_NODE_PAGE'
export const REQUEST_MORE_NODE_PAGE = 'REQUEST_MORE_NODE_PAGE' 
export const END_REQUEST_NODE_PAGE = 'END_REQUEST_NODE_PAGE'

export const USER_LOGIN = 'USER_LOGIN'
export const USER_LOGOUT = 'USER_LOGOUT'
export const END_USER_LOGOUT = 'END_USER_LOGOUT'

export const REQUEST_USER = 'REQUEST_USER'
export const RECEIVE_USER = 'RECEIVE_USER'

export const REQUEST_USER_TOPIC_LIST = 'REQUEST_USER_TOPIC_LIST'
export const RECEIVE_USER_TOPIC_LIST = 'RECEIVE_USER_TOPIC_LIST'

export const REQUEST_USER_REPLY_LIST = 'REQUEST_USER_REPLY_LIST'
export const RECEIVE_USER_REPLY_LIST = 'RECEIVE_USER_REPLY_LIST'

export const REQUEST_FOCUS_USER = 'REQUEST_FOCUS_USER'
export const END_REQUEST_FOCUS_USER = 'END_REQUEST_FOCUS_USER'

export const REQUEST_BLOCK_USER = 'REQUEST_BLOCK_USER'
export const END_REQUEST_BLOCK_USER = 'END_REQUEST_BLOCK_USER'

export const REQUEST_MY_TOPIC = 'REQUEST_MORE_MY_TOPIC'
export const REQUEST_MORE_MY_TOPIC = 'REQUEST_MY_TOPIC'

export const RECEIVE_MY_TOPIC = 'RECEIVE_MY_TOPIC'
export const REFRESH_MY_TOPIC = 'REFRESH_MY_TOPIC'

export const REQUEST_MY_REPLY = 'REQUEST_MY_REPLY'
export const REQUEST_MORE_MY_REPLY = 'REQUEST_MORE_MY_REPLY'

export const RECEIVE_MY_REPLY = 'RECEIVE_MY_REPLY'
export const REFRESH_MY_REPLY = 'REFRESH_MY_REPLY'

export const REQUEST_MY_NODE = 'REQUEST_MY_NODE'
export const RECEIVE_MY_NODE = 'RECEIVE_MY_NODE'

export const REQUEST_MY_FAVORITE_TOPIC = 'REQUEST_MY_FAVORITE_TOPIC'
export const REFRESH_MY_FAVORITE_TOPIC = 'REFRESH_MY_FAVORITE_TOPIC'
export const REQUEST_MORE_MY_FAVORITE_TOPIC = 'REQUEST_MORE_MY_FAVORITE_TOPIC'
export const RECEIVE_MY_FAVORITE_TOPIC = 'RECEIVE_MY_FAVORITE_TOPIC'


export const REQUEST_MY_FOCUS_PERSON = 'REQUEST_MY_FOCUS_PERSON'
export const REFRESH_MY_FOCUS_PERSON = 'REFRESH_MY_FOCUS_PERSON'
export const REQUEST_MORE_MY_FOCUS_PERSON = 'REQUEST_MORE_MY_FOCUS_PERSON'
export const RECEIVE_MY_FOCUS_PERSON = 'RECEIVE_MY_FOCUS_PERSON'


export const REQUEST_MY_NOTIFICATION = 'REQUEST_MY_NOTIFICATION'
export const REFRESH_MY_NOTIFICATION = 'REFRESH_MY_NOTIFICATION'
export const REQUEST_MORE_MY_NOTIFICATION = 'REQUEST_MORE_MY_NOTIFICATION'
export const RECEIVE_MY_NOTIFICATION = 'RECEIVE_MY_NOTIFICATION'
export const DELETE_MY_NOTIFICATION = 'DELETE_MY_NOTIFICATION'
export const END_DELETE_MY_NOTIFICATION = 'END_DELETE_MY_NOTIFICATION'


export const ADD_ACCOUNT_PAGE_INIT = 'ADD_ACCOUNT_PAGE_INIT'
export const EDIT_ACCOUNT_PAGE_INIT = 'EDIT_ACCOUNT_PAGE_INIT'
export const ACCOUNT_DELETE = 'ACCOUNTS_DELETE'
export const USER_RECEIVE = 'USER_RECEIVE'
export const USER_CHECK_START = 'USER_CHECK_START'
export const USER_CHECK_END = 'USER_CHECK_END'
export const CHANGE_USER_START = 'CHANGE_USER_START'
//export const CHANGE_USER = 'CHANGE_USER'
export const CHANGE_USER_END = 'CHANGE_USER_END'


export const ADD_ACCOUNT = 'ADD_ACCOUNT'
export const END_ADD_ACCOUNT = 'END_ADD_ACCOUNT'
export const CHANGE_USER = 'CHANGE_USER'
export const END_CHANGE_USER = 'END_CHANGE_USER'
export const DELETE_ACCOUNT = 'DELETE_ACCOUNT'



export const START_SEARCH = 'START_SEACH'
export const RECEIVE_SEARCH = 'RECEIVE_SEARCH'
export const SEARCH_PAGE_CLOSE = 'SEARCH_PAGE_CLOSE'
export const REFRESH_SEARCH = 'REFRESH_SEARCH'
export const SEARCH_NEXT_PAGE = 'SEARCH_NEXT_PAGE'
export const ADD_SEARCH_HISTORY = 'ADD_SEARCH_HISTORY'
export const REMOVE_SEARCH_HISTORY = 'REMOVE_SEARCH_HISTORY'

export const REQUEST_NEW_TOPIC = 'REQUEST_NEW_TOPIC'
export const RECEIVE_NEW_TOPIC = 'RECEIVE_NEW_TOPIC'
export const POST_NEW_TOPIC = 'POST_NEW_TOPIC'
export const END_POST_NEW_TOPIC = 'END_POST_NEW_TOPIC'

