


export const TEST_A = 'TEST_A'
export const TEST_B = 'TEST_B'

export const REQUEST_TOPIC = 'REQUEST_TOPIC'
export const RECEIVE_TOPIC = 'RECEIVE_TOPIC'

export const START_FAVORITE_TOPIC = 'START_FAVORITE_TOPIC'
export const END_FAVORITE_TOPIC = 'END_FAVORITE_TOPIC'

export const START_THANK_TOPIC = 'START_THANK_TOPIC'
export const END_THANK_TOPIC = 'END_THANK_TOPIC'

export const START_REPLY_TOPIC = 'START_REPLY_TOPIC'
export const END_REPLY_TOPIC = 'END_REPLY_TOPIC'


export const START_THANK_REPLY = 'START_THANK_REPLY'
export const END_THANK_REPLY = 'END_THANK_REPLY'


export const REQUEST_TOPIC_LIST = 'REQUEST_TOPIC_LIST'
export const RECEIVE_TOPIC_LIST = 'RECEIVE_TOPIC_LIST'

export const REQUEST_NODE_LIST = 'REQUEST_NODE_LIST'
export const RECEIVE_NODE_LIST = 'RECEIVE_NODE_LIST'


export const USER_LOGIN = 'USER_LOGIN'
export const USER_LOGOUT = 'USER_LOGOUT'

export const REQUEST_USER = 'REQUEST_USER'
export const RECEIVE_USER = 'RECEIVE_USER'

export const REQUEST_USER_TOPIC_LIST = 'REQUEST_USER_TOPIC_LIST'
export const RECEIVE_USER_TOPIC_LIST = 'RECEIVE_USER_TOPIC_LIST'


export const REQUEST_USER_REPLY_LIST = 'REQUEST_USER_REPLY_LIST'
export const RECEIVE_USER_REPLY_LIST = 'RECEIVE_USER_REPLY_LIST'

export const REQUEST_MY_TOPIC = 'REQUEST_MORE_MY_TOPIC'
export const REQUEST_MORE_MY_TOPIC = 'REQUEST_MY_TOPIC'

export const RECEIVE_MY_TOPIC = 'RECEIVE_MY_TOPIC'
export const REFRESH_MY_TOPIC = 'REFRESH_MY_TOPIC'

export const REQUEST_MY_REPLY = 'REQUEST_MY_REPLY'
export const REQUEST_MORE_MY_REPLY = 'REQUEST_MORE_MY_REPLY'

export const RECEIVE_MY_REPLY = 'RECEIVE_MY_REPLY'
export const REFRESH_MY_REPLY = 'REFRESH_MY_REPLY'


export const ADD_ACCOUNT_PAGE_INIT = 'ADD_ACCOUNT_PAGE_INIT'
export const EDIT_ACCOUNT_PAGE_INIT = 'EDIT_ACCOUNT_PAGE_INIT'
export const ACCOUNT_ADD = 'ACCOUNTS_ADD'
export const ACCOUNT_DELETE = 'ACCOUNTS_DELETE'
export const USER_RECEIVE = 'USER_RECEIVE'
export const USER_CHECK_START = 'USER_CHECK_START'
export const USER_CHECK_END = 'USER_CHECK_END'
export const CHANGE_USER_START = 'CHANGE_USER_START'
export const CHANGE_USER = 'CHANGE_USER'
export const CHANGE_USER_END = 'CHANGE_USER_END'